# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170210_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars', verbose_name='\u0444\u043e\u0442\u043e'),
        ),
    ]
