# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170422_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvalidation',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='\u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='accountvalidation',
            name='confirmed_date',
            field=models.DateTimeField(verbose_name='\u0434\u0430\u0442\u0430 \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u044f'),
        ),
    ]
