# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170422_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail address'),
        ),
    ]
