# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170422_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvalidation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
