# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170422_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvalidation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
