# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountvalidation',
            name='id',
        ),
        migrations.AlterField(
            model_name='accountvalidation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID  '),
        ),
    ]
