# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20170311_1047'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchat',
            unique_together=set([]),
        ),
    ]
