# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_auto_20170311_1251'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchat',
            unique_together=set([('user', 'chat')]),
        ),
    ]
