# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20170311_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=1024, verbose_name='\u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435'),
        ),
    ]
