# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': '\u0421\u043e\u0431\u044b\u0442\u0438\u0435', 'verbose_name_plural': '\u0421\u043e\u0431\u044b\u0442\u0438\u044f'},
        ),
    ]
