# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 12:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to=settings.AUTH_USER_MODEL, verbose_name='\u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044c')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0437\u0430\u043f\u0440\u043e\u0441 \u0434\u0440\u0443\u0436\u0431\u044b',
                'verbose_name_plural': '\u0437\u0430\u043f\u0440\u043e\u0441\u044b \u0434\u0440\u0443\u0436\u0431\u044b',
            },
        ),
        migrations.AlterUniqueTogether(
            name='friendshiprequest',
            unique_together=set([('initiator', 'recipient')]),
        ),
    ]
